name: Publish website
on:
  push:
    branches:
      - master
  workflow_dispatch: # 允许手动触发工作流
permissions:
  contents: read
  pages: write  # 增加权限以推送到GitHub Pages

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [lts/*]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Build the website
        run: npx gulp web

      - name: Create website directory
        run: mkdir website

      - name: Copy build files to website directory
        run: cp -r build/gh-pages/* website/

      - name: Add, commit, and push to current branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add website
          git commit -m "Add website directory with build files" || echo "No changes to commit"
          git push || echo "Push failed"
        env:
          GIT_PUSH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # 
